version: 1

formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"
  colored:
    (): colorlog.ColoredFormatter
    format: "%(asctime)s - %(log_color)s%(levelname)s%(reset)s - %(filename)s:%(lineno)d - %(blue)s%(message)s"
    datefmt: "%H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  out:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs.log
    mode: a
    encoding: utf-8

root:
  level: DEBUG
  handlers: [console, file]

loggers:
  pyrogram:
    level: WARNING

disable_existing_loggers: false
